spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dangerousanimal?serverTimezone=GMT%2B8&useSSL=true
      username: root
      password: 123456

server:
  port: 8080
