spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.134.119.175:3306/zzstest?serverTimezone=GMT%2B8&useSSL=true
      username: zzstest
      password: hPythrZC62ite4RT

server:
  port: 8080  #不知道会不会和部署到阿里云上的端口号冲突 断言：应该是阿里云上的端口号优先 因为通过命令行指定的优先级最高